[package]
name = "tftp_server"
version = "0.0.2"
authors = ["Darin Minamoto <darinm223@gmail.com>"]
description = "A TFTP server implementation in Rust using mio"
repository = "https://github.com/DarinM223/tftp-server"
readme = "README.md"
keywords = ["network", "tftp", "protocol", "mio"]
license = "MIT"

[dependencies]
mio = "0.6"
rand = "0.3"
byteorder = "0.5"
log = "0.3.6"
env_logger = "0.3.5"

[dev-dependencies]
env_logger = "0.3.5"

[lib]
name = "tftp_server"
path = "src/lib.rs"

[[bin]]
name = "tftp_server_bin"
path = "src/bin.rs"

[[test]]
name = "tftp-packet-tests"
path = "tests/test_packet.rs"

[[test]]
name = "tftp-server-tests"
path = "tests/test_server.rs"
harness = false
